version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.2

jobs:
  build-and-test:
    executor:
      name: node/defualt
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run: npm run test
      - codecov/upload:
          file: { { coverage_report_filepath } }
workflows:
  verification:
    jobs:
      - build-and-test
